import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import "./globals.css";
import { inter } from "./fonts/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const theme = cookies().get("__theme__")?.value || "system";

	return (
		<html lang="en">
			<body className={`${inter.className}  antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
